### ISSUE TITLE
[BUG] Doesn't play any of SomaFM streams

### ISSUE THREAD

**Issue by zkvsky** [MikMuellerDev/radio#4]
Example:

```
id = "sfm_defcon" # An arbitrary (unique) ID for the stream
name = "SomaFM DEFCON" # A user-friendly name
description = "Music for Hacking. The DEF CON Year-Round Channel." # A user-friendly description
url = "https://ice4.somafm.com/defcon-128-aac" # The MP3 source of the stream
image_file = "sfm_defcon.png" # The image file inside the `image` directory
auto_restart = true # Whether the stream should be restarted if it stops of fails
auto_start = false # Whether the stream should play as soon as the service is launched

```

There's no error in the log it just fails to load in the UI

**Comment by zkvsky** [comment]
Flac streams from RadioParadise won't play either....
https://radioparadise.com/listen/stream-links

All of my streams are either aac or flac, I don't use mp3

**Comment by MikMuellerDev** [comment]
Hello, thanks for opening the issue.
Currently, only MP3 is supported.
I am sorry to inform you that i do not have capacity to work on this project at the moment. If you do have time and energy, please feel free to contribute.
The best i can do is to create an error which informs the user that the stream is not compatible.
If you really need to use software to stream any non-mp3 software, consider unsing the [predecessor](https://github.com/MikMuellerDev/radiGo) of radio.

**Comment by zkvsky** [comment]
> Hello, thanks for opening the issue. Currently, only MP3 is supported. I am sorry to inform you that i do not have capacity to work on this project at the moment. If you do have time and energy, please feel free to contribute. The best i can do is to create an error which informs the user that the stream is not compatible. If you really need to use software to stream any non-mp3 software, consider unsing the [predecessor](https://github.com/MikMuellerDev/radiGo) of radio.

Perhaps consider displaying that info at the top of readme somewhere?

**Comment by MikMuellerDev** [comment]
Sure, that's a good idea.
Updated it on the README.
